################################################################################
################################################################################
################################################################################
#
# This Compose file will bring up the standalone Omniverse Navigator 
# stack.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
# It is of utmost importance to configure your 
# navigator.env. 
#
# Review it in FULL and configure it's values as desired. 
# 
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

version: "3.7"

services:
  navigator:
    image: ${REGISTRY}/nucleus-navigator:${NAV3_VERSION}
    restart: always
    tty: true
    restart: always

    environment:

      ACCEPT_EULA: "${ACCEPT_EULA:?ACCEPT_EULA must be set to 1}"

      PUBLIC_URL: /

      SSL: ${SSL_ENABLED}
      SSL_CERT: /omni/secrets/SSL_CERT
      SSL_KEY: /omni/secrets/SSL_KEY

    volumes:

      - type: bind
        source:  ${SSL_CERT}
        target: /omni/secrets/SSL_CERT
        read_only: true

      - type: bind
        source:  ${SSL_KEY}
        target: /omni/secrets/SSL_KEY
        read_only: true

    ports:

      - published: ${WEB_SSL_PORT}
        target: 443

      - published: ${WEB_PORT}
        target: 80

networks: 
  default: 
    ipam:
      config: 
        - subnet: "${CONTAINER_SUBNET}"


